Start testing: Jan 31 22:28 +06
----------------------------------------------------------
1/11 Testing: incorrect_solution_tests
1/11 Test: incorrect_solution_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/incorrect_solution_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"incorrect_solution_tests" start time: Jan 31 22:28 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LRUCacheTest
[ RUN      ] LRUCacheTest.GetFromEmptyCacheShouldThrow
[       OK ] LRUCacheTest.GetFromEmptyCacheShouldThrow (0 ms)
[ RUN      ] LRUCacheTest.CapacityAndSize
[       OK ] LRUCacheTest.CapacityAndSize (0 ms)
[ RUN      ] LRUCacheTest.BasicPutGet
[       OK ] LRUCacheTest.BasicPutGet (0 ms)
[ RUN      ] LRUCacheTest.Eviction
[       OK ] LRUCacheTest.Eviction (0 ms)
[ RUN      ] LRUCacheTest.UsageOrderCheck
[       OK ] LRUCacheTest.UsageOrderCheck (0 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_NoExpirationIfZero
[       OK ] LRUCacheTest.ExpirationTime_NoExpirationIfZero (55 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_BasicExpiry
[       OK ] LRUCacheTest.ExpirationTime_BasicExpiry (65 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ResetOnAccess
[       OK ] LRUCacheTest.ExpirationTime_ResetOnAccess (218 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp:151: Failure
Expected: switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("cache.get(\"First\")", "111", cache.get("First"), 111))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp", 151, gtest_ar.failure_message()) = ::testing::Message() doesn't throw an exception.
  Actual: it throws std::runtime_error with description "Key not found in cache".

[  FAILED  ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate (64 ms)
[ RUN      ] LRUCacheTest.PutAll_Basic
[       OK ] LRUCacheTest.PutAll_Basic (0 ms)
[ RUN      ] LRUCacheTest.PutAll_CapacityOverflow
[       OK ] LRUCacheTest.PutAll_CapacityOverflow (0 ms)
[ RUN      ] LRUCacheTest.PutAll_WithExpirationTime
[       OK ] LRUCacheTest.PutAll_WithExpirationTime (65 ms)
[----------] 12 tests from LRUCacheTest (469 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (469 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate

 1 FAILED TEST
<end of output>
Test time =   0.48 sec
----------------------------------------------------------
Test Failed.
"incorrect_solution_tests" end time: Jan 31 22:28 +06
"incorrect_solution_tests" time elapsed: 00:00:00
----------------------------------------------------------

2/11 Testing: model1_tests
2/11 Test: model1_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model1_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model1_tests" start time: Jan 31 22:28 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LRUCacheTest
[ RUN      ] LRUCacheTest.GetFromEmptyCacheShouldThrow
[       OK ] LRUCacheTest.GetFromEmptyCacheShouldThrow (0 ms)
[ RUN      ] LRUCacheTest.CapacityAndSize
[       OK ] LRUCacheTest.CapacityAndSize (0 ms)
[ RUN      ] LRUCacheTest.BasicPutGet
[       OK ] LRUCacheTest.BasicPutGet (0 ms)
[ RUN      ] LRUCacheTest.Eviction
[       OK ] LRUCacheTest.Eviction (0 ms)
[ RUN      ] LRUCacheTest.UsageOrderCheck
[       OK ] LRUCacheTest.UsageOrderCheck (0 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_NoExpirationIfZero
[       OK ] LRUCacheTest.ExpirationTime_NoExpirationIfZero (55 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_BasicExpiry
[       OK ] LRUCacheTest.ExpirationTime_BasicExpiry (61 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ResetOnAccess
[       OK ] LRUCacheTest.ExpirationTime_ResetOnAccess (220 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp:151: Failure
Expected: switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("cache.get(\"First\")", "111", cache.get("First"), 111))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp", 151, gtest_ar.failure_message()) = ::testing::Message() doesn't throw an exception.
  Actual: it throws std::runtime_error with description "Key not found in cache".

[  FAILED  ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate (63 ms)
[ RUN      ] LRUCacheTest.PutAll_Basic
[       OK ] LRUCacheTest.PutAll_Basic (0 ms)
[ RUN      ] LRUCacheTest.PutAll_CapacityOverflow
[       OK ] LRUCacheTest.PutAll_CapacityOverflow (0 ms)
[ RUN      ] LRUCacheTest.PutAll_WithExpirationTime
[       OK ] LRUCacheTest.PutAll_WithExpirationTime (61 ms)
[----------] 12 tests from LRUCacheTest (462 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (462 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate

 1 FAILED TEST
<end of output>
Test time =   0.48 sec
----------------------------------------------------------
Test Failed.
"model1_tests" end time: Jan 31 22:28 +06
"model1_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model10_tests
3/11 Testing: model10_tests
3/11 Test: model10_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model10_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model10_tests" end time: Jan 31 22:28 +06
"model10_tests" time elapsed: 00:00:00
----------------------------------------------------------

4/11 Testing: model2_tests
4/11 Test: model2_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model2_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model2_tests" start time: Jan 31 22:28 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LRUCacheTest
[ RUN      ] LRUCacheTest.GetFromEmptyCacheShouldThrow
[       OK ] LRUCacheTest.GetFromEmptyCacheShouldThrow (0 ms)
[ RUN      ] LRUCacheTest.CapacityAndSize
[       OK ] LRUCacheTest.CapacityAndSize (0 ms)
[ RUN      ] LRUCacheTest.BasicPutGet
[       OK ] LRUCacheTest.BasicPutGet (0 ms)
[ RUN      ] LRUCacheTest.Eviction
[       OK ] LRUCacheTest.Eviction (0 ms)
[ RUN      ] LRUCacheTest.UsageOrderCheck
[       OK ] LRUCacheTest.UsageOrderCheck (0 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_NoExpirationIfZero
[       OK ] LRUCacheTest.ExpirationTime_NoExpirationIfZero (55 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_BasicExpiry
<end of output>
Test time =   0.15 sec
----------------------------------------------------------
Test Failed.
"model2_tests" end time: Jan 31 22:28 +06
"model2_tests" time elapsed: 00:00:00
----------------------------------------------------------

5/11 Testing: model3_tests
5/11 Test: model3_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model3_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model3_tests" start time: Jan 31 22:28 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LRUCacheTest
[ RUN      ] LRUCacheTest.GetFromEmptyCacheShouldThrow
[       OK ] LRUCacheTest.GetFromEmptyCacheShouldThrow (0 ms)
[ RUN      ] LRUCacheTest.CapacityAndSize
[       OK ] LRUCacheTest.CapacityAndSize (0 ms)
[ RUN      ] LRUCacheTest.BasicPutGet
[       OK ] LRUCacheTest.BasicPutGet (0 ms)
[ RUN      ] LRUCacheTest.Eviction
[       OK ] LRUCacheTest.Eviction (0 ms)
[ RUN      ] LRUCacheTest.UsageOrderCheck
[       OK ] LRUCacheTest.UsageOrderCheck (0 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_NoExpirationIfZero
[       OK ] LRUCacheTest.ExpirationTime_NoExpirationIfZero (55 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_BasicExpiry
[       OK ] LRUCacheTest.ExpirationTime_BasicExpiry (63 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ResetOnAccess
[       OK ] LRUCacheTest.ExpirationTime_ResetOnAccess (218 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp:151: Failure
Expected: switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("cache.get(\"First\")", "111", cache.get("First"), 111))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp", 151, gtest_ar.failure_message()) = ::testing::Message() doesn't throw an exception.
  Actual: it throws std::runtime_error with description "Key has expired".

[  FAILED  ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate (64 ms)
[ RUN      ] LRUCacheTest.PutAll_Basic
[       OK ] LRUCacheTest.PutAll_Basic (0 ms)
[ RUN      ] LRUCacheTest.PutAll_CapacityOverflow
[       OK ] LRUCacheTest.PutAll_CapacityOverflow (0 ms)
[ RUN      ] LRUCacheTest.PutAll_WithExpirationTime
[       OK ] LRUCacheTest.PutAll_WithExpirationTime (62 ms)
[----------] 12 tests from LRUCacheTest (464 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (464 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate

 1 FAILED TEST
<end of output>
Test time =   0.47 sec
----------------------------------------------------------
Test Failed.
"model3_tests" end time: Jan 31 22:28 +06
"model3_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model4_tests
6/11 Testing: model4_tests
6/11 Test: model4_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model4_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model4_tests" end time: Jan 31 22:28 +06
"model4_tests" time elapsed: 00:00:00
----------------------------------------------------------

7/11 Testing: model5_tests
7/11 Test: model5_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model5_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model5_tests" start time: Jan 31 22:28 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LRUCacheTest
[ RUN      ] LRUCacheTest.GetFromEmptyCacheShouldThrow
[       OK ] LRUCacheTest.GetFromEmptyCacheShouldThrow (0 ms)
[ RUN      ] LRUCacheTest.CapacityAndSize
[       OK ] LRUCacheTest.CapacityAndSize (0 ms)
[ RUN      ] LRUCacheTest.BasicPutGet
[       OK ] LRUCacheTest.BasicPutGet (0 ms)
[ RUN      ] LRUCacheTest.Eviction
[       OK ] LRUCacheTest.Eviction (0 ms)
[ RUN      ] LRUCacheTest.UsageOrderCheck
[       OK ] LRUCacheTest.UsageOrderCheck (0 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_NoExpirationIfZero
[       OK ] LRUCacheTest.ExpirationTime_NoExpirationIfZero (54 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_BasicExpiry
<end of output>
Test time =   0.14 sec
----------------------------------------------------------
Test Failed.
"model5_tests" end time: Jan 31 22:28 +06
"model5_tests" time elapsed: 00:00:00
----------------------------------------------------------

8/11 Testing: model6_tests
8/11 Test: model6_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model6_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model6_tests" start time: Jan 31 22:28 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 12 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 12 tests from LRUCacheTest
[ RUN      ] LRUCacheTest.GetFromEmptyCacheShouldThrow
[       OK ] LRUCacheTest.GetFromEmptyCacheShouldThrow (0 ms)
[ RUN      ] LRUCacheTest.CapacityAndSize
[       OK ] LRUCacheTest.CapacityAndSize (0 ms)
[ RUN      ] LRUCacheTest.BasicPutGet
[       OK ] LRUCacheTest.BasicPutGet (0 ms)
[ RUN      ] LRUCacheTest.Eviction
[       OK ] LRUCacheTest.Eviction (0 ms)
[ RUN      ] LRUCacheTest.UsageOrderCheck
[       OK ] LRUCacheTest.UsageOrderCheck (0 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_NoExpirationIfZero
[       OK ] LRUCacheTest.ExpirationTime_NoExpirationIfZero (55 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_BasicExpiry
[       OK ] LRUCacheTest.ExpirationTime_BasicExpiry (65 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ResetOnAccess
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp:129: Failure
Expected: switch (0) case 0: default: if (const ::testing::AssertionResult gtest_ar = (::testing::internal::EqHelper::Compare("cache.get(\"K\")", "123", cache.get("K"), 123))) ; else ::testing::internal::AssertHelper(::testing::TestPartResult::kNonFatalFailure, "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/test.cpp", 129, gtest_ar.failure_message()) = ::testing::Message() doesn't throw an exception.
  Actual: it throws std::runtime_error with description "Key has expired".

[  FAILED  ] LRUCacheTest.ExpirationTime_ResetOnAccess (219 ms)
[ RUN      ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate
[       OK ] LRUCacheTest.ExpirationTime_ExistingKeysNotAffectedUntilUpdate (63 ms)
[ RUN      ] LRUCacheTest.PutAll_Basic
[       OK ] LRUCacheTest.PutAll_Basic (0 ms)
[ RUN      ] LRUCacheTest.PutAll_CapacityOverflow
[       OK ] LRUCacheTest.PutAll_CapacityOverflow (0 ms)
[ RUN      ] LRUCacheTest.PutAll_WithExpirationTime
[       OK ] LRUCacheTest.PutAll_WithExpirationTime (61 ms)
[----------] 12 tests from LRUCacheTest (465 ms total)

[----------] Global test environment tear-down
[==========] 12 tests from 1 test suite ran. (465 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] LRUCacheTest.ExpirationTime_ResetOnAccess

 1 FAILED TEST
<end of output>
Test time =   0.47 sec
----------------------------------------------------------
Test Failed.
"model6_tests" end time: Jan 31 22:28 +06
"model6_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model7_tests
9/11 Testing: model7_tests
9/11 Test: model7_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model7_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model7_tests" end time: Jan 31 22:28 +06
"model7_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model8_tests
10/11 Testing: model8_tests
10/11 Test: model8_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model8_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model8_tests" end time: Jan 31 22:28 +06
"model8_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build/model9_tests
11/11 Testing: model9_tests
11/11 Test: model9_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621208/build
"model9_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model9_tests" end time: Jan 31 22:28 +06
"model9_tests" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jan 31 22:28 +06
