Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Development/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Development/incorrect_solution_tests

1: Test command: 
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
 1/11 Test  #1: incorrect_solution_tests .........***Not Run   0.00 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
2: Test timeout computed to be: 5
2: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
2: [==========] Running 6 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 6 tests from DijkstraTest
2: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
2: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
2: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
2: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
2: [ RUN      ] DijkstraTest.NegativeCycleDetection
2: [       OK ] DijkstraTest.NegativeCycleDetection (0 ms)
2: [ RUN      ] DijkstraTest.UnreachableNodes
2: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
2: [ RUN      ] DijkstraTest.EmptyGraph
2: [       OK ] DijkstraTest.EmptyGraph (0 ms)
2: [ RUN      ] DijkstraTest.WrongInput
2: [       OK ] DijkstraTest.WrongInput (0 ms)
2: [----------] 6 tests from DijkstraTest (0 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 6 tests from 1 test suite ran. (0 ms total)
2: [  PASSED  ] 6 tests.
 2/11 Test  #2: model1_tests .....................   Passed    0.60 sec
test 3
      Start  3: model10_tests

3: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model10_tests
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
3: Test timeout computed to be: 5
3: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
3: [==========] Running 6 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 6 tests from DijkstraTest
3: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
3: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
3: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
3: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
3: [ RUN      ] DijkstraTest.NegativeCycleDetection
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:57: Failure
3: Expected equality of these values:
3:   distances[0]
3:     Which is: -10
3:   0
3: 
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:59: Failure
3: Expected equality of these values:
3:   distances[2]
3:     Which is: -6
3:   0
3: 
3: [  FAILED  ] DijkstraTest.NegativeCycleDetection (0 ms)
3: [ RUN      ] DijkstraTest.UnreachableNodes
3: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
3: [ RUN      ] DijkstraTest.EmptyGraph
3: [       OK ] DijkstraTest.EmptyGraph (0 ms)
3: [ RUN      ] DijkstraTest.WrongInput
3: [       OK ] DijkstraTest.WrongInput (0 ms)
3: [----------] 6 tests from DijkstraTest (0 ms total)
3: 
3: [----------] Global test environment tear-down
3: [==========] 6 tests from 1 test suite ran. (0 ms total)
3: [  PASSED  ] 5 tests.
3: [  FAILED  ] 1 test, listed below:
3: [  FAILED  ] DijkstraTest.NegativeCycleDetection
3: 
3:  1 FAILED TEST
 3/11 Test  #3: model10_tests ....................***Failed    0.35 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
4: Test timeout computed to be: 5
4: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
4: [==========] Running 6 tests from 1 test suite.
4: [----------] Global test environment set-up.
4: [----------] 6 tests from DijkstraTest
4: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
4: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
4: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
4: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
4: [ RUN      ] DijkstraTest.NegativeCycleDetection
4: [       OK ] DijkstraTest.NegativeCycleDetection (0 ms)
4: [ RUN      ] DijkstraTest.UnreachableNodes
4: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
4: [ RUN      ] DijkstraTest.EmptyGraph
4: [       OK ] DijkstraTest.EmptyGraph (0 ms)
4: [ RUN      ] DijkstraTest.WrongInput
4: [       OK ] DijkstraTest.WrongInput (0 ms)
4: [----------] 6 tests from DijkstraTest (0 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 6 tests from 1 test suite ran. (0 ms total)
4: [  PASSED  ] 6 tests.
 4/11 Test  #4: model2_tests .....................   Passed    0.36 sec
test 5
      Start  5: model3_tests

5: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model3_tests
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
5: Test timeout computed to be: 5
5: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
5: [==========] Running 6 tests from 1 test suite.
5: [----------] Global test environment set-up.
5: [----------] 6 tests from DijkstraTest
5: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
5: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
5: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
5: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
5: [ RUN      ] DijkstraTest.NegativeCycleDetection
5: [       OK ] DijkstraTest.NegativeCycleDetection (0 ms)
5: [ RUN      ] DijkstraTest.UnreachableNodes
5: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
5: [ RUN      ] DijkstraTest.EmptyGraph
5: [       OK ] DijkstraTest.EmptyGraph (0 ms)
5: [ RUN      ] DijkstraTest.WrongInput
5: [       OK ] DijkstraTest.WrongInput (0 ms)
5: [----------] 6 tests from DijkstraTest (0 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 6 tests from 1 test suite ran. (0 ms total)
5: [  PASSED  ] 6 tests.
 5/11 Test  #5: model3_tests .....................   Passed    0.40 sec
test 6
      Start  6: model4_tests

6: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model4_tests
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
6: Test timeout computed to be: 5
6: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
6: [==========] Running 6 tests from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 6 tests from DijkstraTest
6: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
6: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
6: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
6: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
6: [ RUN      ] DijkstraTest.NegativeCycleDetection
6: [       OK ] DijkstraTest.NegativeCycleDetection (0 ms)
6: [ RUN      ] DijkstraTest.UnreachableNodes
6: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
6: [ RUN      ] DijkstraTest.EmptyGraph
6: [       OK ] DijkstraTest.EmptyGraph (0 ms)
6: [ RUN      ] DijkstraTest.WrongInput
6: [       OK ] DijkstraTest.WrongInput (0 ms)
6: [----------] 6 tests from DijkstraTest (0 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 6 tests from 1 test suite ran. (0 ms total)
6: [  PASSED  ] 6 tests.
 6/11 Test  #6: model4_tests .....................   Passed    0.35 sec
test 7
      Start  7: model5_tests

7: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model5_tests
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
7: Test timeout computed to be: 5
7: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
7: [==========] Running 6 tests from 1 test suite.
7: [----------] Global test environment set-up.
7: [----------] 6 tests from DijkstraTest
7: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
7: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
7: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
7: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
7: [ RUN      ] DijkstraTest.NegativeCycleDetection
7: [       OK ] DijkstraTest.NegativeCycleDetection (0 ms)
7: [ RUN      ] DijkstraTest.UnreachableNodes
7: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
7: [ RUN      ] DijkstraTest.EmptyGraph
7: [       OK ] DijkstraTest.EmptyGraph (0 ms)
7: [ RUN      ] DijkstraTest.WrongInput
7: [       OK ] DijkstraTest.WrongInput (0 ms)
7: [----------] 6 tests from DijkstraTest (0 ms total)
7: 
7: [----------] Global test environment tear-down
7: [==========] 6 tests from 1 test suite ran. (0 ms total)
7: [  PASSED  ] 6 tests.
 7/11 Test  #7: model5_tests .....................   Passed    0.37 sec
test 8
      Start  8: model6_tests

8: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model6_tests
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
8: Test timeout computed to be: 5
8: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
8: [==========] Running 6 tests from 1 test suite.
8: [----------] Global test environment set-up.
8: [----------] 6 tests from DijkstraTest
8: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
8: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
8: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
8: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
8: [ RUN      ] DijkstraTest.NegativeCycleDetection
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:57: Failure
8: Expected equality of these values:
8:   distances[0]
8:     Which is: -10
8:   0
8: 
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:59: Failure
8: Expected equality of these values:
8:   distances[2]
8:     Which is: -6
8:   0
8: 
8: [  FAILED  ] DijkstraTest.NegativeCycleDetection (0 ms)
8: [ RUN      ] DijkstraTest.UnreachableNodes
8: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
8: [ RUN      ] DijkstraTest.EmptyGraph
8: [       OK ] DijkstraTest.EmptyGraph (0 ms)
8: [ RUN      ] DijkstraTest.WrongInput
8: [       OK ] DijkstraTest.WrongInput (0 ms)
8: [----------] 6 tests from DijkstraTest (0 ms total)
8: 
8: [----------] Global test environment tear-down
8: [==========] 6 tests from 1 test suite ran. (0 ms total)
8: [  PASSED  ] 5 tests.
8: [  FAILED  ] 1 test, listed below:
8: [  FAILED  ] DijkstraTest.NegativeCycleDetection
8: 
8:  1 FAILED TEST
 8/11 Test  #8: model6_tests .....................***Failed    0.35 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
9: Test timeout computed to be: 5
9: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
9: [==========] Running 6 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 6 tests from DijkstraTest
9: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
9: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
9: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
9: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
9: [ RUN      ] DijkstraTest.NegativeCycleDetection
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:57: Failure
9: Expected equality of these values:
9:   distances[0]
9:     Which is: -10
9:   0
9: 
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:59: Failure
9: Expected equality of these values:
9:   distances[2]
9:     Which is: -6
9:   0
9: 
9: [  FAILED  ] DijkstraTest.NegativeCycleDetection (0 ms)
9: [ RUN      ] DijkstraTest.UnreachableNodes
9: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
9: [ RUN      ] DijkstraTest.EmptyGraph
9: [       OK ] DijkstraTest.EmptyGraph (0 ms)
9: [ RUN      ] DijkstraTest.WrongInput
9: [       OK ] DijkstraTest.WrongInput (0 ms)
9: [----------] 6 tests from DijkstraTest (0 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 6 tests from 1 test suite ran. (0 ms total)
9: [  PASSED  ] 5 tests.
9: [  FAILED  ] 1 test, listed below:
9: [  FAILED  ] DijkstraTest.NegativeCycleDetection
9: 
9:  1 FAILED TEST
 9/11 Test  #9: model7_tests .....................***Failed    0.35 sec
test 10
      Start 10: model8_tests

10: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model8_tests
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
10: Test timeout computed to be: 5
10: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_depErrors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
s/googletest-src/googletest/src/gtest_main.cc
10: [==========] Running 6 tests from 1 test suite.
10: [----------] Global test environment set-up.
10: [----------] 6 tests from DijkstraTest
10: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
10: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
10: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
10: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
10: [ RUN      ] DijkstraTest.NegativeCycleDetection
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:57: Failure
10: Expected equality of these values:
10:   distances[0]
10:     Which is: -10
10:   0
10: 
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:59: Failure
10: Expected equality of these values:
10:   distances[2]
10:     Which is: -6
10:   0
10: 
10: [  FAILED  ] DijkstraTest.NegativeCycleDetection (0 ms)
10: [ RUN      ] DijkstraTest.UnreachableNodes
10: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
10: [ RUN      ] DijkstraTest.EmptyGraph
10: [       OK ] DijkstraTest.EmptyGraph (0 ms)
10: [ RUN      ] DijkstraTest.WrongInput
10: [       OK ] DijkstraTest.WrongInput (0 ms)
10: [----------] 6 tests from DijkstraTest (0 ms total)
10: 
10: [----------] Global test environment tear-down
10: [==========] 6 tests from 1 test suite ran. (0 ms total)
10: [  PASSED  ] 5 tests.
10: [  FAILED  ] 1 test, listed below:
10: [  FAILED  ] DijkstraTest.NegativeCycleDetection
10: 
10:  1 FAILED TEST
10/11 Test #10: model8_tests .....................***Failed    0.38 sec
test 11
      Start 11: model9_tests

11: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/model9_tests
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
11: Test timeout computed to be: 5
11: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/_deps/googletest-src/googletest/src/gtest_main.cc
11: [==========] Running 6 tests from 1 test suite.
11: [----------] Global test environment set-up.
11: [----------] 6 tests from DijkstraTest
11: [ RUN      ] DijkstraTest.PositiveNoNegativeEdges
11: [       OK ] DijkstraTest.PositiveNoNegativeEdges (0 ms)
11: [ RUN      ] DijkstraTest.NegativeEdgeWeightsNoCycle
11: [       OK ] DijkstraTest.NegativeEdgeWeightsNoCycle (0 ms)
11: [ RUN      ] DijkstraTest.NegativeCycleDetection
11: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:57: Failure
11: Expected equality of these values:
11:   distances[0]
11:     Which is: -10
11:   0
11: 
11: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/test.cpp:59: Failure
11: Expected equality of these values:
11:   distances[2]
11:     Which is: -6
11:   0
11: 
11: [  FAILED  ] DijkstraTest.NegativeCycleDetection (0 ms)
11: [ RUN      ] DijkstraTest.UnreachableNodes
11: [       OK ] DijkstraTest.UnreachableNodes (0 ms)
11: [ RUN      ] DijkstraTest.EmptyGraph
11: [       OK ] DijkstraTest.EmptyGraph (0 ms)
11: [ RUN      ] DijkstraTest.WrongInput
11: [       OK ] DijkstraTest.WrongInput (0 ms)
11: [----------] 6 tests from DijkstraTest (0 ms total)
11: 
11: [----------] Global test environment tear-down
11: [==========] 6 tests from 1 test suite ran. (0 ms total)
11: [  PASSED  ] 5 tests.
11: [  FAILED  ] 1 test, listed below:
11: [  FAILED  ] DijkstraTest.NegativeCycleDetection
11: 
11:  1 FAILED TEST
11/11 Test #11: model9_tests .....................***Failed    0.36 sec

45% tests passed, 6 tests failed out of 11

Total Test time (real) =   3.90 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Not Run)
	  3 - model10_tests (Failed)
	  8 - model6_tests (Failed)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Failed)
	 11 - model9_tests (Failed)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build
      Start  1: incorrect_solution_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Release/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Release/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Debug/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Debug/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/MinSizeRel/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/MinSizeRel/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/RelWithDebInfo/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/RelWithDebInfo/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Deployment/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Deployment/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Development/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Development/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Development/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Development/incorrect_solution_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Not Run   0.00 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................   Passed    0.02 sec
      Start  3: model10_tests
 3/11 Test  #3: model10_tests ....................***Failed    0.02 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................   Passed    0.02 sec
      Start  5: model3_tests
 5/11 Test  #5: model3_tests .....................   Passed    0.02 sec
      Start  6: model4_tests
 6/11 Test  #6: model4_tests .....................   Passed    0.02 sec
      Start  7: model5_tests
 7/11 Test  #7: model5_tests .....................   Passed    0.02 sec
      Start  8: model6_tests
 8/11 Test  #8: model6_tests .....................***Failed    0.02 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................***Failed    0.02 sec
      Start 10: model8_tests
10/11 Test #10: model8_tests .....................***Failed    0.02 sec
      Start 11: model9_tests
11/11 Test #11: model9_tests .....................***Failed    0.02 sec

45% tests passed, 6 tests failed out of 11

Total Test time (real) =   0.21 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Not Run)
	  3 - model10_tests (Failed)
	  8 - model6_tests (Failed)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Failed)
	 11 - model9_tests (Failed)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473609/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
