UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests

1: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/incorrect_solution_tests
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
1: Test timeout computed to be: 5
1: [==========] Running 4 tests from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 4 tests from SudokuSolverTests
1: [ RUN      ] SudokuSolverTests.SolvableSudoku
1: [       OK ] SudokuSolverTests.SolvableSudoku (1 ms)
1: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
1: [       OK ] SudokuSolverTests.UnsolvableSudoku (4 ms)
1: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:103: Failure
1: Value of: solveSudoku(board)
1:   Actual: false
1: Expected: true
1: Should return true for an already solved board.
1: 
1: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
1: [ RUN      ] SudokuSolverTests.EmptySudoku
1: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
1: [----------] 4 tests from SudokuSolverTests (5 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 4 tests from 1 test suite ran. (6 ms total)
1: [  PASSED  ] 3 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku
1: 
1:  1 FAILED TEST
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.89 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
2: Test timeout computed to be: 5
2: [==========] Running 4 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 4 tests from SudokuSolverTests
2: [ RUN      ] SudokuSolverTests.SolvableSudoku
2: [       OK ] SudokuSolverTests.SolvableSudoku (1 ms)
2: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
2: [       OK ] SudokuSolverTests.UnsolvableSudoku (0 ms)
2: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:103: Failure
2: Value of: solveSudoku(board)
2:   Actual: false
2: Expected: true
2: Should return true for an already solved board.
2: 
2: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
2: [ RUN      ] SudokuSolverTests.EmptySudoku
2: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
2: [----------] 4 tests from SudokuSolverTests (2 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 4 tests from 1 test suite ran. (2 ms total)
2: [  PASSED  ] 3 tests.
2: [  FAILED  ] 1 test, listed below:
2: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku
2: 
2:  1 FAILED TEST
 2/11 Test  #2: model1_tests .....................***Failed    0.37 sec
test 3
      Start  3: model10_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Release/model10_tests
Users/ittehad/DocumeUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
nts/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Release/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Debug/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Debug/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/MinSizeRel/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/MinSizeRel/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/RelWithDebInfo/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/RelWithDebInfo/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Deployment/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Deployment/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Development/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Development/model10_tests

3: Test command: 
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
 3/11 Test  #3: model10_tests ....................***Not Run   0.00 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
4: Test timeout computed to be: 5
4: [==========] Running 4 tests from 1 test suite.
4: [----------] Global test environment set-up.
4: [----------] 4 tests from SudokuSolverTests
4: [ RUN      ] SudokuSolverTests.SolvableSudoku
4: [       OK ] SudokuSolverTests.SolvableSudoku (1 ms)
4: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
4: [       OK ] SudokuSolverTests.UnsolvableSudoku (3 ms)
4: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
4: [       OK ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
4: [ RUN      ] SudokuSolverTests.EmptySudoku
4: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
4: [----------] 4 tests from SudokuSolverTests (5 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 4 tests from 1 test suite ran. (5 ms total)
4: [  PASSED  ] 4 tests.
 4/11 Test  #4: model2_tests .....................   Passed    0.45 sec
test 5
      Start  5: model3_tests

5: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model3_tests
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
5: Test timeout computed to be: 5
5: [==========] Running 4 tests from 1 test suite.
5: [----------] Global test environment set-up.
5: [----------] 4 tests from SudokuSolverTests
5: [ RUN      ] SudokuSolverTests.SolvableSudoku
5: [       OK ] SudokuSolverTests.SolvableSudoku (1 ms)
5: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
5: [       OK ] SudokuSolverTests.UnsolvableSudoku (3 ms)
5: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:103: Failure
5: Value of: solveSudoku(board)
5:   Actual: false
5: Expected: true
5: Should return true for an already solved board.
5: 
5: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
5: [ RUN      ] SudokuSolverTests.EmptySudoku
5: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
5: [----------] 4 tests from SudokuSolverTests (5 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 4 tests from 1 test suite ran. (6 ms total)
5: [  PASSED  ] 3 tests.
5: [  FAILED  ] 1 test, listed below:
5: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku
5: 
5:  1 FAILED TEST
 5/11 Test  #5: model3_tests .....................***Failed    0.37 sec
test 6
      Start  6: model4_tests

6: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model4_tests
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
6: Test timeout computed to be: 5
6: [==========] Running 4 tests from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 4 tests from SudokuSolverTests
6: [ RUN      ] SudokuSolverTests.SolvableSudoku
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:65: Failure
6: Value of: isValidCompletedSudoku(board)
6:   Actual: false
6: Expected: true
6: Solution does not satisfy Sudoku constraints.
6: 
6: [  FAILED  ] SudokuSolverTests.SolvableSudoku (1 ms)
6: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
6: [       OK ] SudokuSolverTests.UnsolvableSudoku (3 ms)
6: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
6: [       OK ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
6: [ RUN      ] SudokuSolverTests.EmptySudoku
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:111: Failure
6: Value of: isValidCompletedSudoku(board)
6:   Actual: false
6: Expected: true
6: The filled board doesn't meet Sudoku constraints.
6: 
6: [  FAILED  ] SudokuSolverTests.EmptySudoku (0 ms)
6: [----------] 4 tests from SudokuSolverTests (5 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 4 tests from 1 test suite ran. (5 ms total)
6: [  PASSED  ] 2 tests.
6: [  FAILED  ] 2 tests, listed below:
6: [  FAILED  ] SudokuSolverTests.SolvableSudoku
6: [  FAILED  ] SudokuSolverTests.EmptySudoku
6: 
6:  2 FAILED TESTS
 6/11 Test  #6: model4_tests .....................***Failed    0.38 sec
test 7
      Start  7: model5_tests

7: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model5_tests
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
7: Test timeout computed to be: 5
7: [==========] Running 4 tests from 1 test suite.
7: [----------] Global test environment set-up.
7: [----------] 4 tests from SudokuSolverTests
7: [ RUN      ] SudokuSolverTests.SolvableSudoku
7: [       OK ] SudokuSolverTests.SolvableSudoku (1 ms)
7: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
7: [       OK ] SudokuSolverTests.UnsolvableSudoku (3 ms)
7: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
7: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:103: Failure
7: Value of: solveSudoku(board)
7:   Actual: false
7: Expected: true
7: Should return true for an already solved board.
7: 
7: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
7: [ RUN      ] SudokuSolverTests.EmptySudoku
7: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
7: [----------] 4 tests from SudokuSolverTests (5 ms total)
7: 
7: [----------] Global test environment tear-down
7: [==========] 4 tests from 1 test suite ran. (5 ms total)
7: [  PASSED  ] 3 tests.
7: [  FAILED  ] 1 test, listed below:
7: [  FAILED  ] SudokuSolverTests.AlreadySolvedSudoku
7: 
7:  1 FAILED TEST
 7/11 Test  #7: model5_tests .....................***Failed    0.37 sec
test 8
      Start  8: model6_tests

8: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model6_tests
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
8: Test timeout computed to be: 5
8: [==========] Running 4 tests from 1 test suite.
8: [----------] Global test environment set-up.
8: [----------] 4 tests from SudokuSolverTests
8: [ RUN      ] SudokuSolverTests.SolvableSudoku
8: [       OK ] SudokuSolverTests.SolvableSudoku (2 ms)
8: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
8: [       OK ] SudokuSolverTests.UnsolvableSudoku (2 ms)
8: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
8: [       OK ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
8: [ RUN      ] SudokuSolverTests.EmptySudoku
8: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
8: [----------] 4 tests from SudokuSolverTests (5 ms total)
8: 
8: [----------] Global test environment tear-down
8: [==========] 4 tests from 1 test suite ran. (5 ms total)
8: [  PASSED  ] 4 tests.
 8/11 Test  #8: model6_tests .....................   Passed    0.37 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
9: Test timeout computed to be: 5
9: [==========] Running 4 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 4 tests from SudokuSolverTests
9: [ RUN      ] SudokuSolverTests.SolvableSudoku
9: [       OK ] SudokuSolverTests.SolvableSudoku (2 ms)
9: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
9: [       OK ] SudokuSolverTests.UnsolvableSudoku (2 ms)
9: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
9: [       OK ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
9: [ RUN      ] SudokuSolverTests.EmptySudoku
9: [       OK ] SudokuSolverTests.EmptySudoku (0 ms)
9: [----------] 4 tests from SudokuSolverTests (5 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 4 tests from 1 test suite ran. (5 ms total)
9: [  PASSED  ] 4 tests.
 9/11 Test  #9: model7_tests .....................   Passed    0.37 sec
test 10
      Start 10: model8_tests

10: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model8_tests
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
10: Test timeout computed to be: 5
10: [==========] Running 4 tests from 1 test suite.
10: [----------] Global test environment set-up.
10: [----------] 4 tests from SudokuSolverTests
10: [ RUN      ] SudokuSolverTests.SolvableSudoku
10/11 Test #10: model8_tests .....................***Exception: SegFault  0.40 sec
test 11
      Start 11: model9_tests

11: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model9_tests
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
11: Test timeout computed to be: 5
11: [==========] Running 4 tests from 1 test suite.
11: [----------] Global test environment set-up.
11: [----------] 4 tests from SudokuSolverTests
11: [ RUN      ] SudokuSolverTests.SolvableSudoku
11: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:65: Failure
11: Value of: isValidCompletedSudoku(board)
11:   Actual: false
11: Expected: true
11: Solution does not satisfy Sudoku constraints.
11: 
11: [  FAILED  ] SudokuSolverTests.SolvableSudoku (0 ms)
11: [ RUN      ] SudokuSolverTests.UnsolvableSudoku
11: [       OK ] SudokuSolverTests.UnsolvableSudoku (3 ms)
11: [ RUN      ] SudokuSolverTests.AlreadySolvedSudoku
11: [       OK ] SudokuSolverTests.AlreadySolvedSudoku (0 ms)
11: [ RUN      ] SudokuSolverTests.EmptySudoku
11: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/test.cpp:111: Failure
11: Value of: isValidCompletedSudoku(board)
11:   Actual: false
11: Expected: true
11: The filled board doesn't meet Sudoku constraints.
11: 
11: [  FAILED  ] SudokuSolverTests.EmptySudoku (0 ms)
11: [----------] 4 tests from SudokuSolverTests (3 ms total)
11: 
11: [----------] Global test environment tear-down
11: [==========] 4 tests from 1 test suite ran. (3 ms total)
11: [  PASSED  ] 2 tests.
11: [  FAILED  ] 2 tests, listed below:
11: [  FAILED  ] SudokuSolverTests.SolvableSudoku
11: [  FAILED  ] SudokuSolverTests.EmptySudoku
11: 
11:  2 FAILED TESTS
11/11 Test #11: model9_tests .....................***Failed    0.49 sec

27% tests passed, 8 tests failed out of 11

Total Test time (real) =   4.48 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Not Run)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Failed)
	 10 - model8_tests (SEGFAULT)
	 11 - model9_tesErrors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
ts (Failed)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build
      Start  1: incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.03 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................***Failed    0.02 sec
      Start  3: model10_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Release/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Release/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Debug/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Debug/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/MinSizeRel/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/MinSizeRel/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/RelWithDebInfo/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/RelWithDebInfo/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Deployment/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Deployment/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Development/model10_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Development/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Release/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Release/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Debug/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Debug/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/MinSizeRel/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/MinSizeRel/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/RelWithDebInfo/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/RelWithDebInfo/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Deployment/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Deployment/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Development/model10_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Development/model10_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/model10_tests
 3/11 Test  #3: model10_tests ....................***Not Run   0.00 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................   Passed    0.02 sec
      Start  5: model3_tests
 5/11 Test  #5: model3_tests .....................***Failed    0.02 sec
      Start  6: model4_tests
 6/11 Test  #6: model4_tests .....................***Failed    0.02 sec
      Start  7: model5_tests
 7/11 Test  #7: model5_tests .....................***Failed    0.02 sec
      Start  8: model6_tests
 8/11 Test  #8: model6_tests .....................   Passed    0.02 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................   Passed    0.03 sec
      Start 10: model8_tests
10/11 Test #10: model8_tests .....................***Exception: SegFault  0.03 sec
      Start 11: model9_tests
11/11 Test #11: model9_tests .....................***Failed    0.02 sec

27% tests passed, 8 tests failed out of 11

Total Test time (real) =   0.25 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Not Run)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Failed)
	 10 - model8_tests (SEGFAULT)
	 11 - model9_tests (Failed)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304016/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
