UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests

1: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/incorrect_solution_tests
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
1: Test timeout computed to be: 5
1: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
1: [==========] Running 13 tests from 2 test suites.
1: [----------] Global test environment set-up.
1: [----------] 3 tests from FreqBufferBasicTest
1: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
1: [       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
1: [ RUN      ] FreqBufferBasicTest.PutAndGet
1: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
1: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
1: [       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
1: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
1: 
1: [----------] 10 tests from FreqBufferExtendedTest
1: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
1: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
1: [       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
1: Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
1:   Actual: it throws nothing.
1: 
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
1: Expected equality of these values:
1:   buffer.capacity()
1:     Which is: 18446744073709551615
1:   3u
1:     Which is: 3
1: 
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
1: Expected equality of these values:
1:   buffer.size()
1:     Which is: 1
1:   0u
1:     Which is: 0
1: 
1: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
1: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
1: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
1: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
1: [       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
1: [       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
1: [       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
1: [ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
1: Expected equality of these values:
1:   buffer.size()
1:     Which is: 0
1:   1u
1:     Which is: 1
1: 
1: unknown file: Failure
1: C++ exception with description "Key not found in FreqBuffer" thrown in the test body.
1: 
1: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
1: [----------] 10 tests from FreqBufferExtendedTest (0 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 13 tests from 2 test suites ran. (1 ms total)
1: [  PASSED  ] 11 tests.
1: [  FAILED  ] 2 tests, listed below:
1: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
1: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
1: 
1:  2 FAILED TESTS
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.54 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
2: Test timeout computed to be: 5
2: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
2: [==========] Running 13 tests from 2 test suites.
2: [----------] Global test environment set-up.
2: [----------] 3 tests from FreqBufferBasicTest
2: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
2: [       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
2: [ RUN      ] FreqBufferBasicTest.PutAndGet
2: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
2: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
2: [       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
2: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
2: 
2: [----------] 10 tests from FreqBufferExtendedTest
2: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
2: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
2: [       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
2: Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
2:   Actual: it throws nothing.
2: 
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
2: Expected equality of these values:
2:   buffer.capacity()
2:     Which is: 18446744073709551615
2:   3u
2:     Which is: 3
2: 
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
2: Expected equality of these values:
2:   buffer.size()
2:     Which is: 1
2:   0u
2:     Which is: 0
2: 
2: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
2: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
2: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
2: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
2: [       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
2: [       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
2: [       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
2: [ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
2: Expected equality of these values:
2:   buffer.size()
2:     Which is: 0
2:   1u
2:     Which is: 1
2: 
2: unknown file: Failure
2: C++ exception with description "Key not found in FreqBuffer" thrown in the test body.
2: 
2: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
2: [----------] 10 tests from FreqBufferExtendedTest (0 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 13 tests from 2 test suites ran. (0 ms total)
2: [  PASSED  ] 11 tests.
2: [  FAILED  ] 2 tests, listed below:
2: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
2: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
2: 
2:  2 FAILED TESTS
 2/11 Test  #2: model1_tests .....................***Failed    0.35 sec
test 3
      Start  3: model10_tests

3: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model10_tests
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
3: Test timeout computed to be: 5
3: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
3: [==========] Running 13 tests from 2 test suites.
3: [----------] Global test environment set-up.
3: [----------] 3 tests from FreqBufferBasicTest
3: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
3: [       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
3: [ RUN      ] FreqBufferBasicTest.PutAndGet
3: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
3: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
3: [       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
3: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
3: 
3: [----------] 10 tests from FreqBufferExtendedTest
3: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
3: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
3: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
3: [       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
3: [ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
3: Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
3:   Actual: it throws nothing.
3: 
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
3: Expected equality of these values:
3:   buffer.capacity()
3:     Which is: 18446744073709551615
3:   3u
3:     Which is: 3
3: 
 3/11 Test  #3: model10_tests ....................Subprocess aborted***Exception:   0.35 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
4: Test timeout computed to be: 5
4: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
4: [==========] Running 13 tests from 2 test suites.
4: [----------] Global test environment set-up.
4: [----------] 3 tests from FreqBufferBasicTest
4: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
4: [       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
4: [ RUN      ] FreqBufferBasicTest.PutAndGet
4: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
4: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
4: [       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
4: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
4: 
4: [----------] 10 tests from FreqBufferExtendedTest
4: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
4: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
4: [       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
4: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
4: Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
4:   Actual: it throws nothing.
4: 
4: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
4: Expected equality of these values:
4:   buffer.capacity()
4:     Which is: 18446744073709551615
4:   3u
4:     Which is: 3
4: 
4: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
4: Expected equality of these values:
4:   buffer.size()
4:     Which is: 1
4:   0u
4:     Which is: 0
4: 
4: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
4: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
4: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
4: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
4: [       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
4: [       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
4: [       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
4: [ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
4: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
4: Expected equality of these values:
4:   buffer.size()
4:     Which is: 0
4:   1u
4:     Which is: 1
4: 
4: unknown file: Failure
4: C++ exception with description "Key not found in FreqBuffer" thrown in the test body.
4: 
4: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
4: [----------] 10 tests from FreqBufferExtendedTest (0 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 13 tests from 2 test suites ran. (0 ms total)
4: [  PASSED  ] 11 tests.
4: [  FAILED  ] 2 tests, listed below:
4: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
4: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
4: 
4:  2 FAILED TESTS
 4/11 Test  #4: model2_tests .....................***Failed    0.38 sec
test 5
      Start  5: model3_tests

5: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model3_tests
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
5: Test timeout computed to be: 5
5: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
5: [==========] Running 13 tests from 2 test suites.
5: [----------] Global test environment set-up.
5: [----------] 3 tests from FreqBufferBasicTest
5: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
5: [       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
5: [ RUN      ] FreqBufferBasicTest.PutAndGet
5: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
5: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
5: [       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
5: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
5: 
5: [----------] 10 tests from FreqBufferExtendedTest
5: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
5: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
5: [       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
5: Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
5:   Actual: it throws nothing.
5: 
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
5: Expected equality of these values:
5:   buffer.capacity()
5:     Which is: 18446744073709551615
5:   3u
5:     Which is: 3
5: 
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
5: Expected equality of these values:
5:   buffer.size()
5:     Which is: 1
5:   0u
5:     Which is: 0
5: 
5: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
5: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
5: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
5: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
5: [       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
5: [       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
5: [       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
5: [ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
5: Expected equality of these values:
5:   buffer.size()
5:     Which is: 0
5:   1u
5:     Which is: 1
5: 
5: unknown file: Failure
5: C++ exception with description "Key not found in FreqBuffer" thrown in the test body.
5: 
5: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
5: [----------] 10 tests from FreqBufferExtendedTest (0 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 13 tests from 2 test suites ran. (0 ms total)
5: [  PASSED  ] 11 tests.
5: [  FAILED  ] 2 tests, listed below:
5: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
5: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
5: 
5:  2 FAILED TESTS
 5/11 Test  #5: model3_tests .....................***Failed    0.33 sec
test 6
      Start  6: model4_tests

6: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model4_tests
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
6: Test timeout computed to be: 5
6: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
6: [==========] Running 13 tests from 2 test suites.
6: [----------] Global test environment set-up.
6: [----------] 3 tests from FreqBufferBasicTest
6: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
6: [       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
6: [ RUN      ] FreqBufferBasicTest.PutAndGet
6: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
6: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
6: [       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
6: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
6: 
6: [----------] 10 tests from FreqBufferExtendedTest
6: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
6: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
6: [       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
6: Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
6:   Actual: it throws nothing.
6: 
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
6: Expected equality of these values:
6:   buffer.capacity()
6:     Which is: 18446744073709551615
6:   3u
6:     Which is: 3
6: 
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
6: Expected equality of these values:
6:   buffer.size()
6:     Which is: 1
6:   0u
6:     Which is: 0
6: 
6: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
6: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
6: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
6: [       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
6: [       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
6: [       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
6: [       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
6: [ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
6: Expected equality of these values:
6:   buffer.size()
6:     Which is: 0
6:   1u
6:     Which is: 1
6: 
6: unknown file: Failure
6: C++ exception with description "Key not found in FreqBuffer" thrown in the test body.
6: 
6: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
6: [----------] 10 tests from FreqBufferExtendedTest (0 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 13 tests from 2 test suites ran. (0 ms total)
6: [  PASSED  ] 11 tests.
6: [  FAILED  ] 2 tests, listed below:
6: [  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
6: [  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
6: 
6:  2 FAILED TESTS
 6/11 Test  #6: model4_tests .....................***Failed    0.33 sec
test 7
      Start  7: model5_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model5_tests

7: Test command: 
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
 7/11 Test  #7: model5_tests .....................***Not Run   0.00 sec
test 8
      Start  8: model6_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model6_tests
Users/ittehad/DocumentsUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model6_tests

8: Test command: 
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
 8/11 Test  #8: model6_tests .....................***Not Run   0.00 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
9: Test timeout computed to be: 5
9: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
9: [==========] Running 13 tests from 2 test suites.
9: [----------] Global test environment set-up.
9: [----------] 3 tests from FreqBufferBasicTest
9: [ RUN      ] FreqBufferBasicTest.CapacityAndSize
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:22: Failure
9: Expected: (buffer.size()) <= (3u), actual: 4 vs 3
9: 
9: [  FAILED  ] FreqBufferBasicTest.CapacityAndSize (0 ms)
9: [ RUN      ] FreqBufferBasicTest.PutAndGet
9: [       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
9: [ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:59: Failure
9: Expected: buffer.get("C") throws an exception of type std::runtime_error.
9:   Actual: it throws nothing.
9: 
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:64: Failure
9: Expected equality of these values:
9:   buffer.size()
9:     Which is: 4
9:   3u
9:     Which is: 3
9: 
9: [  FAILED  ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
9: [----------] 3 tests from FreqBufferBasicTest (0 ms total)
9: 
9: [----------] 10 tests from FreqBufferExtendedTest
9: [ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
9: [       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
9: [ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
 9/11 Test  #9: model7_tests .....................***Exception: SegFault  0.36 sec
test 10
      Start 10: model8_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSiUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
zeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model8_tests

10: Test command: 
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
10/11 Test #10: model8_tests .....................***Not Run   0.00 sec
test 11
      Start 11: model9_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model9_tests

11: Test command: 
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
11/11 Test #11: model9_tests .....................***Not Run   0.00 sec

0% tests passed, 11 tests failed out of 11

Total Test time (real) =   2.65 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Subprocess aborted)
	  4 - model2_tests (Failed)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Not Run)
	  8 - model6_tests (Not Run)
	  9 - model7_tests (SEGFAULT)
	 10 - model8_tests (Not Run)
	 11 - model9_tests (Not Run)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
      Start  1: incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.01 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................***Failed    0.01 sec
      Start  3: model10_tests
 3/11 Test  #3: model10_tests ....................Subprocess aborted***Exception:   0.02 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................***Failed    0.00 sec
      Start  5: model3_tests
 5/11 Test  #5: model3_tests .....................***Failed    0.00 sec
      Start  6: model4_tests
 6/11 Test  #6: model4_tests .....................***Failed    0.00 sec
      Start  7: model5_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model5_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model5_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model5_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
 7/11 Test  #7: model5_tests .....................***Not Run   0.00 sec
      Start  8: model6_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model6_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
 8/11 Test  #8: model6_tests .....................***Not Run   0.00 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................***Exception: SegFault  0.01 sec
      Start 10: model8_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model8_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
10/11 Test #10: model8_tests .....................***Not Run   0.00 sec
      Start 11: model9_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Development/model9_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
11/11 Test #11: model9_tests .....................***Not Run   0.00 sec

0% tests passed, 11 tests failed out of 11

Total Test time (real) =   0.06 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Subprocess aborted)
	  4 - model2_tests (Failed)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Not Run)
	  8 - model6_tests (Not Run)
	  9 - model7_tests (SEGFAULT)
	 10 - model8_tests (Not Run)
	 11 - model9_tests (Not Run)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
