UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests

1: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/incorrect_solution_tests
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
1: Test timeout computed to be: 5
1: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
1: [==========] Running 5 tests from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 5 tests from ParseEthernetPacketTest
1: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
1: CRC: 0x4222484890
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/test.cpp:32: Failure
1: Expected equality of these values:
1:   parsedFields["CRC Validation"]
1:     Which is: "Invalid"
1:   "Valid"
1: 
1: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
1: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
1: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
1: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
1: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
1: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
1: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
1: [ RUN      ] ParseEthernetPacketTest.ShortPacket
1: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
1: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 5 tests from 1 test suite ran. (0 ms total)
1: [  PASSED  ] 4 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest
1: 
1:  1 FAILED TEST
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.41 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
2: Test timeout computed to be: 5
2: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
2: [==========] Running 5 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 5 tests from ParseEthernetPacketTest
2: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
2: CRC: 0x4222484890
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/test.cpp:32: Failure
2: Expected equality of these values:
2:   parsedFields["CRC Validation"]
2:     Which is: "Invalid"
2:   "Valid"
2: 
2: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
2: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
2: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
2: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
2: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
2: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
2: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
2: [ RUN      ] ParseEthernetPacketTest.ShortPacket
2: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
2: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 5 tests from 1 test suite ran. (0 ms total)
2: [  PASSED  ] 4 tests.
2: [  FAILED  ] 1 test, listed below:
2: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest
2: 
2:  1 FAILED TEST
 2/11 Test  #2: model1_tests .....................***Failed    0.32 sec
test 3
      Start  3: model10_tests

3: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model10_tests
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
3: Test timeout computed to be: 5
3: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
3: [==========] Running 5 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 5 tests from ParseEthernetPacketTest
3: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
3: CRC: 0x4222484890
3: [       OK ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
3: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
3: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
3: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
3: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
3: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
3: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
3: [ RUN      ] ParseEthernetPacketTest.ShortPacket
3: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
3: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
3: 
3: [----------] Global test environment tear-down
3: [==========] 5 tests from 1 test suite ran. (0 ms total)
3: [  PASSED  ] 5 tests.
 3/11 Test  #3: model10_tests ....................   Passed    0.32 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
4: Test timeout computed to be: 5
4: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
4: [==========] Running 5 tests from 1 test suite.
4: [----------] Global test environment set-up.
4: [----------] 5 tests from ParseEthernetPacketTest
4: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
4: CRC: 0x4222484890
4: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/test.cpp:32: Failure
4: Expected equality of these values:
4:   parsedFields["CRC Validation"]
4:     Which is: "Invalid"
4:   "Valid"
4: 
4: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
4: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
4: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
4: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
4: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
4: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
4: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
4: [ RUN      ] ParseEthernetPacketTest.ShortPacket
4: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
4: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 5 tests from 1 test suite ran. (0 ms total)
4: [  PASSED  ] 4 tests.
4: [  FAILED  ] 1 test, listed below:
4: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest
4: 
4:  1 FAILED TEST
 4/11 Test  #4: model2_tests .....................***Failed    0.31 sec
test 5
      Start  5: model3_tests

5: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model3_tests
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
5: Test timeout computed to be: 5
5: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
5: [==========] Running 5 tests from 1 test suite.
5: [----------] Global test environment set-up.
5: [----------] 5 tests from ParseEthernetPacketTest
5: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
5: CRC: 0x4222484890
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/test.cpp:32: Failure
5: Expected equality of these values:
5:   parsedFields["CRC Validation"]
5:     Which is: "Invalid"
5:   "Valid"
5: 
5: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
5: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
5: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
5: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
5: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
5: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
5: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
5: [ RUN      ] ParseEthernetPacketTest.ShortPacket
5: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
5: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 5 tests from 1 test suite ran. (0 ms total)
5: [  PASSED  ] 4 tests.
5: [  FAILED  ] 1 test, listed below:
5: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest
5: 
5:  1 FAILED TEST
 5/11 Test  #5: model3_tests .....................***Failed    0.37 sec
test 6
      Start  6: model4_tests

6: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model4_tests
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
6: Test timeout computed to be: 5
6: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
6: [==========] Running 5 tests from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 5 tests from ParseEthernetPacketTest
6: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
6: CRC: 0x4222484890
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/test.cpp:32: Failure
6: Expected equality of these values:
6:   parsedFields["CRC Validation"]
6:     Which is: "Invalid"
6:   "Valid"
6: 
6: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
6: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
6: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
6: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
6: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
6: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
6: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
6: [ RUN      ] ParseEthernetPacketTest.ShortPacket
6: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
6: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 5 tests from 1 test suite ran. (0 ms total)
6: [  PASSED  ] 4 tests.
6: [  FAILED  ] 1 test, listed below:
6: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest
6: 
6:  1 FAILED TEST
 6/11 Test  #6: model4_tests .....................***Failed    0.41 sec
test 7
      Start  7: model5_tests

7: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model5_tests
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
7: Test timeout computed to be: 5
7: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
7: [==========] Running 5 tests from 1 test suite.
7: [----------] Global test environment set-up.
7: [----------] 5 tests from ParseEthernetPacketTest
7: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
7: CRC: 0x4222484890
7: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/test.cpp:32: Failure
7: Expected equality of these values:
7:   parsedFields["CRC Validation"]
7:     Which is: "Invalid"
7:   "Valid"
7: 
7: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
7: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
7: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
7: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
7: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
7: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
7: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
7: [ RUN      ] ParseEthernetPacketTest.ShortPacket
7: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
7: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
7: 
7: [----------] Global test environment tear-down
7: [==========] 5 tests from 1 test suite ran. (0 ms total)
7: [  PASSED  ] 4 tests.
7: [  FAILED  ] 1 test, listed below:
7: [  FAILED  ] ParseEthernetPacketTest.ValidPacketTest
7: 
7:  1 FAILED TEST
 7/11 Test  #7: model5_tests .....................***Failed    0.32 sec
test 8
      Start  8: model6_tests

8: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model6_tests
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
8: Test timeout computed to be: 5
8: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
8: [==========] Running 5 tests from 1 test suite.
8: [----------] Global test environment set-up.
8: [----------] 5 tests from ParseEthernetPacketTest
8: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
8: CRC: 0x4222484890
8: [       OK ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
8: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
8: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
8: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
8: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
8: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
8: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
8: [ RUN      ] ParseEthernetPacketTest.ShortPacket
8: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
8: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
8: 
8: [----------] Global test environment tear-down
8: [==========] 5 tests from 1 test suite ran. (0 ms total)
8: [  PASSED  ] 5 tests.
 8/11 Test  #8: model6_tests .....................   Passed    0.32 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
9: Test timeout computed to be: 5
9: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
9: [==========] Running 5 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 5 tests from ParseEthernetPacketTest
9: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
9: CRC: 0x4222484890
9: [       OK ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
9: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
9: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
9: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
9: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
9: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
9: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
9: [ RUN      ] ParseEthernetPacketTest.ShortPacket
9: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
9: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 5 tests from 1 test suite ran. (0 ms total)
9: [  PASSED  ] 5 tests.
 9/11 Test  #9: model7_tests .....................   Passed    0.32 sec
test 10
      Start 10: model8_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Users/iUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
ttehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Development/model8_tests

10: Test command: 
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
10/11 Test #10: model8_tests .....................***Not Run   0.00 sec
test 11
      Start 11: model9_tests

11: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model9_tests
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
11: Test timeout computed to be: 5
11: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/_deps/googletest-src/googletest/src/gtest_main.cc
11: [==========] Running 5 tests from 1 test suite.
11: [----------] Global test environment set-up.
11: [----------] 5 tests from ParseEthernetPacketTest
11: [ RUN      ] ParseEthernetPacketTest.ValidPacketTest
11: CRC: 0x4222484890
11: [       OK ] ParseEthernetPacketTest.ValidPacketTest (0 ms)
11: [ RUN      ] ParseEthernetPacketTest.InvalidCRC
11: [       OK ] ParseEthernetPacketTest.InvalidCRC (0 ms)
11: [ RUN      ] ParseEthernetPacketTest.EmptyPacket
11: [       OK ] ParseEthernetPacketTest.EmptyPacket (0 ms)
11: [ RUN      ] ParseEthernetPacketTest.UnsupportedEtherType
11: [       OK ] ParseEthernetPacketTest.UnsupportedEtherType (0 ms)
11: [ RUN      ] ParseEthernetPacketTest.ShortPacket
11: [       OK ] ParseEthernetPacketTest.ShortPacket (0 ms)
11: [----------] 5 tests from ParseEthernetPacketTest (0 ms total)
11: 
11: [----------] Global test environment tear-down
11: [==========] 5 tests from 1 test suite ran. (0 ms total)
11: [  PASSED  ] 5 tests.
11/11 Test #11: model9_tests .....................   Passed    0.32 sec

36% tests passed, 7 tests failed out of 11

Total Test time (real) =   3.44 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  4 - model2_tests (Failed)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Failed)
	 10 - model8_tests (Not Run)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build
      Start  1: incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.01 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................***Failed    0.01 sec
      Start  3: model10_tests
 3/11 Test  #3: model10_tests ....................   Passed    0.00 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................***Failed    0.00 sec
      Start  5: model3_tests
 5/11 Test  #5: model3_tests .....................***Failed    0.00 sec
      Start  6: model4_tests
 6/11 Test  #6: model4_tests .....................***Failed    0.00 sec
      Start  7: model5_tests
 7/11 Test  #7: model5_tests .....................***Failed    0.00 sec
      Start  8: model6_tests
 8/11 Test  #8: model6_tests .....................   Passed    0.00 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................   Passed    0.00 sec
      Start 10: model8_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Release/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Release/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Debug/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Debug/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/MinSizeRel/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/MinSizeRel/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/RelWithDebInfo/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/RelWithDebInfo/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Deployment/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Deployment/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Development/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Development/model8_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/model8_tests
10/11 Test #10: model8_tests .....................***Not Run   0.00 sec
      Start 11: model9_tests
11/11 Test #11: model9_tests .....................   Passed    0.00 sec

36% tests passed, 7 tests failed out of 11

Total Test time (real) =   0.05 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  4 - model2_tests (Failed)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Failed)
	 10 - model8_tests (Not Run)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621260/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
