UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests

1: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/incorrect_solution_tests
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
1: Test timeout computed to be: 5
1: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
1: [==========] Running 7 tests from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 7 tests from CacheBufferTest
1: [ RUN      ] CacheBufferTest.BasicOperations
1: [       OK ] CacheBufferTest.BasicOperations (0 ms)
1: [ RUN      ] CacheBufferTest.EvictionPolicy
1: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
1: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
1: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
1: [ RUN      ] CacheBufferTest.BufferUnderLoad
1: [       OK ] CacheBufferTest.BufferUnderLoad (2 ms)
1: [ RUN      ] CacheBufferTest.MergeBuffers
1: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
1: [ RUN      ] CacheBufferTest.BackupAndRestore
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:104: Failure
1: Expected equality of these values:
1:   "one"
1:   buffer.get(1)
1:     Which is: "two"
1: 
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:105: Failure
1: Expected equality of these values:
1:   "two"
1:   buffer.get(2)
1:     Which is: ""
1: 
1: unknown file: Failure
1: C++ exception with description "No backup data available" thrown in the test body.
1: 
1: [  FAILED  ] CacheBufferTest.BackupAndRestore (0 ms)
1: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
1: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
1: [----------] 7 tests from CacheBufferTest (2 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 7 tests from 1 test suite ran. (2 ms total)
1: [  PASSED  ] 6 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] CacheBufferTest.BackupAndRestore
1: 
1:  1 FAILED TEST
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.55 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
2: Test timeout computed to be: 5
2: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
2: [==========] Running 7 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 7 tests from CacheBufferTest
2: [ RUN      ] CacheBufferTest.BasicOperations
2: [       OK ] CacheBufferTest.BasicOperations (0 ms)
2: [ RUN      ] CacheBufferTest.EvictionPolicy
2: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
2: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
2: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
2: [ RUN      ] CacheBufferTest.BufferUnderLoad
2: [       OK ] CacheBufferTest.BufferUnderLoad (3 ms)
2: [ RUN      ] CacheBufferTest.MergeBuffers
2: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
2: [ RUN      ] CacheBufferTest.BackupAndRestore
2: [       OK ] CacheBufferTest.BackupAndRestore (0 ms)
2: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
2: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
2: [----------] 7 tests from CacheBufferTest (3 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 7 tests from 1 test suite ran. (4 ms total)
2: [  PASSED  ] 7 tests.
 2/11 Test  #2: model1_tests .....................   Passed    0.42 sec
test 3
      Start  3: model10_tests

3: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model10_tests
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
3: Test timeout computed to be: 5
3: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
3: [==========] Running 7 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 7 tests from CacheBufferTest
3: [ RUN      ] CacheBufferTest.BasicOperations
3: [       OK ] CacheBufferTest.BasicOperations (0 ms)
3: [ RUN      ] CacheBufferTest.EvictionPolicy
3: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
3: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
3: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
3: [ RUN      ] CacheBufferTest.BufferUnderLoad
3: [       OK ] CacheBufferTest.BufferUnderLoad (2 ms)
3: [ RUN      ] CacheBufferTest.MergeBuffers
3: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
3: [ RUN      ] CacheBufferTest.BackupAndRestore
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:104: Failure
3: Expected equality of these values:
3:   "one"
3:   buffer.get(1)
3:     Which is: "two"
3: 
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:105: Failure
3: Expected equality of these values:
3:   "two"
3:   buffer.get(2)
3:     Which is: ""
3: 
3: unknown file: Failure
3: C++ exception with description "No backup data available" thrown in the test body.
3: 
3: [  FAILED  ] CacheBufferTest.BackupAndRestore (0 ms)
3: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
3: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
3: [----------] 7 tests from CacheBufferTest (2 ms total)
3: 
3: [----------] Global test environment tear-down
3: [==========] 7 tests from 1 test suite ran. (2 ms total)
3: [  PASSED  ] 6 tests.
3: [  FAILED  ] 1 test, listed below:
3: [  FAILED  ] CacheBufferTest.BackupAndRestore
3: 
3:  1 FAILED TEST
 3/11 Test  #3: model10_tests ....................***Failed    0.41 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
4: Test timeout computed to be: 5
4: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
4: [==========] Running 7 tests from 1 test suite.
4: [----------] Global test environment set-up.
4: [----------] 7 tests from CacheBufferTest
4: [ RUN      ] CacheBufferTest.BasicOperations
4: [       OK ] CacheBufferTest.BasicOperations (0 ms)
4: [ RUN      ] CacheBufferTest.EvictionPolicy
4: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
4: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
4: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
4: [ RUN      ] CacheBufferTest.BufferUnderLoad
4: [       OK ] CacheBufferTest.BufferUnderLoad (3 ms)
4: [ RUN      ] CacheBufferTest.MergeBuffers
4: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
4: [ RUN      ] CacheBufferTest.BackupAndRestore
4: [       OK ] CacheBufferTest.BackupAndRestore (0 ms)
4: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
4: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
4: [----------] 7 tests from CacheBufferTest (3 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 7 tests from 1 test suite ran. (3 ms total)
4: [  PASSED  ] 7 tests.
 4/11 Test  #4: model2_tests .....................   Passed    0.32 sec
test 5
      Start  5: model3_tests

5: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model3_tests
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
5: Test timeout computed to be: 5
5: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
5: [==========] Running 7 tests from 1 test suite.
5: [----------] Global test environment set-up.
5: [----------] 7 tests from CacheBufferTest
5: [ RUN      ] CacheBufferTest.BasicOperations
5: [       OK ] CacheBufferTest.BasicOperations (0 ms)
5: [ RUN      ] CacheBufferTest.EvictionPolicy
5: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
5: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
5: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
5: [ RUN      ] CacheBufferTest.BufferUnderLoad
5: [       OK ] CacheBufferTest.BufferUnderLoad (3 ms)
5: [ RUN      ] CacheBufferTest.MergeBuffers
5: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
5: [ RUN      ] CacheBufferTest.BackupAndRestore
5: [       OK ] CacheBufferTest.BackupAndRestore (0 ms)
5: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
5: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
5: [----------] 7 tests from CacheBufferTest (4 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 7 tests from 1 test suite ran. (4 ms total)
5: [  PASSED  ] 7 tests.
 5/11 Test  #5: model3_tests .....................   Passed    0.31 sec
test 6
      Start  6: model4_tests

6: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model4_tests
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
6: Test timeout computed to be: 5
6: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
6: [==========] Running 7 tests from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 7 tests from CacheBufferTest
6: [ RUN      ] CacheBufferTest.BasicOperations
6: [       OK ] CacheBufferTest.BasicOperations (0 ms)
6: [ RUN      ] CacheBufferTest.EvictionPolicy
6: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
6: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
6: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
6: [ RUN      ] CacheBufferTest.BufferUnderLoad
6: [       OK ] CacheBufferTest.BufferUnderLoad (3 ms)
6: [ RUN      ] CacheBufferTest.MergeBuffers
6: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
6: [ RUN      ] CacheBufferTest.BackupAndRestore
6: [       OK ] CacheBufferTest.BackupAndRestore (0 ms)
6: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
6: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
6: [----------] 7 tests from CacheBufferTest (3 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 7 tests from 1 test suite ran. (3 ms total)
6: [  PASSED  ] 7 tests.
 6/11 Test  #6: model4_tests .....................   Passed    0.32 sec
test 7
      Start  7: model5_tests

7: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model5_tests
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
7: Test timeout computed to be: 5
7: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
7: [==========] Running 7 tests from 1 test suite.
7: [----------] Global test environment set-up.
7: [----------] 7 tests from CacheBufferTest
7: [ RUN      ] CacheBufferTest.BasicOperations
7: [       OK ] CacheBufferTest.BasicOperations (0 ms)
7: [ RUN      ] CacheBufferTest.EvictionPolicy
7: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
7: [ RUN      ] CachUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
eBufferTest.DuplicateKeyHandling
7: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
7: [ RUN      ] CacheBufferTest.BufferUnderLoad
7: [       OK ] CacheBufferTest.BufferUnderLoad (3 ms)
7: [ RUN      ] CacheBufferTest.MergeBuffers
7: [       OK ] CacheBufferTest.MergeBuffers (0 ms)
7: [ RUN      ] CacheBufferTest.BackupAndRestore
7: [       OK ] CacheBufferTest.BackupAndRestore (0 ms)
7: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
7: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
7: [----------] 7 tests from CacheBufferTest (3 ms total)
7: 
7: [----------] Global test environment tear-down
7: [==========] 7 tests from 1 test suite ran. (4 ms total)
7: [  PASSED  ] 7 tests.
 7/11 Test  #7: model5_tests .....................   Passed    0.47 sec
test 8
      Start  8: model6_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model6_tests

8: Test command: 
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
 8/11 Test  #8: model6_tests .....................***Not Run   0.00 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
9: Test timeout computed to be: 5
9: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
9: [==========] Running 7 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 7 tests from CacheBufferTest
9: [ RUN      ] CacheBufferTest.BasicOperations
9: [       OK ] CacheBufferTest.BasicOperations (0 ms)
9: [ RUN      ] CacheBufferTest.EvictionPolicy
9: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
9: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
9: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
9: [ RUN      ] CacheBufferTest.BufferUnderLoad
9: [       OK ] CacheBufferTest.BufferUnderLoad (1 ms)
9: [ RUN      ] CacheBufferTest.MergeBuffers
9: unknown file: Failure
9: C++ exception with description "Key not found in CacheBuffer" thrown in the test body.
9: 
9: [  FAILED  ] CacheBufferTest.MergeBuffers (0 ms)
9: [ RUN      ] CacheBufferTest.BackupAndRestore
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:104: Failure
9: Expected equality of these values:
9:   "one"
9:   buffer.get(1)
9:     Which is: "two"
9: 
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:105: Failure
9: Expected equality of these values:
9:   "two"
9:   buffer.get(2)
9:     Which is: ""
9: 
9: [  FAILED  ] CacheBufferTest.BackupAndRestore (0 ms)
9: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
9: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
9: [----------] 7 tests from CacheBufferTest (1 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 7 tests from 1 test suite ran. (1 ms total)
9: [  PASSED  ] 5 tests.
9: [  FAILED  ] 2 tests, listed below:
9: [  FAILED  ] CacheBufferTest.MergeBuffers
9: [  FAILED  ] CacheBufferTest.BackupAndRestore
9: 
9:  2 FAILED TESTS
 9/11 Test  #9: model7_tests .....................***Failed    0.40 sec
test 10
      Start 10: model8_tests

10: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model8_tests
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
10: Test timeout computed to be: 5
10: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/_deps/googletest-src/googletest/src/gtest_main.cc
10: [==========] Running 7 tests from 1 test suite.
10: [----------] Global test environment set-up.
10: [----------] 7 tests from CacheBufferTest
10: [ RUN      ] CacheBufferTest.BasicOperations
10: [       OK ] CacheBufferTest.BasicOperations (0 ms)
10: [ RUN      ] CacheBufferTest.EvictionPolicy
10: [       OK ] CacheBufferTest.EvictionPolicy (0 ms)
10: [ RUN      ] CacheBufferTest.DuplicateKeyHandling
10: [       OK ] CacheBufferTest.DuplicateKeyHandling (0 ms)
10: [ RUN      ] CacheBufferTest.BufferUnderLoad
10: [       OK ] CacheBufferTest.BufferUnderLoad (2 ms)
10: [ RUN      ] CacheBufferTest.MergeBuffers
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:73: Failure
10: Expected equality of these values:
10:   "one"
10:   merged.get(1)
10:     Which is: "four"
10: 
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:74: Failure
10: Expected equality of these values:
10:   "two"
10:   merged.get(2)
10:     Which is: "four"
10: 
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:75: Failure
10: Expected equality of these values:
10:   "three"
10:   merged.get(3)
10:     Which is: "four"
10: 
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:77: Failure
10: Expected equality of these values:
10:   "five"
10:   merged.get(5)
10:     Which is: "four"
10: 
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:86: Failure
10: Expected equality of these values:
10:   "two"
10:   smallerMerged.get(2)
10:     Which is: ""
10: 
10: [  FAILED  ] CacheBufferTest.MergeBuffers (0 ms)
10: [ RUN      ] CacheBufferTest.BackupAndRestore
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:104: Failure
10: Expected equality of these values:
10:   "one"
10:   buffer.get(1)
10:     Which is: "two"
10: 
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/test.cpp:105: Failure
10: Expected equality of these values:
10:   "two"
10:   buffer.get(2)
10:     Which is: ""
10: 
10: [  FAILED  ] CacheBufferTest.BackupAndRestore (0 ms)
10: [ RUN      ] CacheBufferTest.RestoreWithoutBackup
10: [       OK ] CacheBufferTest.RestoreWithoutBackup (0 ms)
10: [----------] 7 tests from CacheBufferTest (3 ms total)
10: 
10: [----------] Global test environment tear-down
10: [==========] 7 tests from 1 test suite ran. (3 ms total)
10: [  PASSED  ] 5 tests.
10: [  FAILED  ] 2 tests, listed below:
10: [  FAILED  ] CacheBufferTest.MergeBuffers
10: [  FAILED  ] CacheBufferTest.BackupAndRestore
10: 
10:  2 FAILED TESTS
10/11 Test #10: model8_tests .....................***Failed    0.36 sec
test 11
     Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
 Start 11: model9_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model9_tests

11: Test command: 
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
11/11 Test #11: model9_tests .....................***Not Run   0.00 sec

45% tests passed, 6 tests failed out of 11

Total Test time (real) =   3.58 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  3 - model10_tests (Failed)
	  8 - model6_tests (Not Run)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Failed)
	 11 - model9_tests (Not Run)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build
      Start  1: incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.01 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................   Passed    0.01 sec
      Start  3: model10_tests
 3/11 Test  #3: model10_tests ....................***Failed    0.01 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................   Passed    0.01 sec
      Start  5: model3_tests
 5/11 Test  #5: model3_tests .....................   Passed    0.01 sec
      Start  6: model4_tests
 6/11 Test  #6: model4_tests .....................   Passed    0.01 sec
      Start  7: model5_tests
 7/11 Test  #7: model5_tests .....................   Passed    0.01 sec
      Start  8: model6_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model6_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model6_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model6_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model6_tests
 8/11 Test  #8: model6_tests .....................***Not Run   0.00 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................***Failed    0.01 sec
      Start 10: model8_tests
10/11 Test #10: model8_tests .....................***Failed    0.01 sec
      Start 11: model9_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model9_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Release/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Debug/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/MinSizeRel/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/RelWithDebInfo/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Deployment/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model9_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Development/model9_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/model9_tests
11/11 Test #11: model9_tests .....................***Not Run   0.00 sec

45% tests passed, 6 tests failed out of 11

Total Test time (real) =   0.06 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  3 - model10_tests (Failed)
	  8 - model6_tests (Not Run)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Failed)
	 11 - model9_tests (Not Run)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473688/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
